### ISSUE TITLE
Cannot download the data and model zip files. Links are not working

### ISSUE THREAD

**Issue by DurgaSandeep25** [tomhosking/separator#1]

**Comment by DurgaSandeep25** [comment]
When i click on the data and model links, they are not getting downloaded. Help me to download them. Thanks :)

**Comment by tomhosking** [comment]
Hi, could you try now?

**Comment by DurgaSandeep25** [comment]
It's still not working. Is it possible to provide a google drive link for the zip files?

**Comment by tomhosking** [comment]
Sorry about this - do these links work?

http://tomho.sk/models/separator/data_paralex.zip
http://tomho.sk/models/separator/data_qqp.zip
http://tomho.sk/models/separator/separator_paralex.zip
http://tomho.sk/models/separator/separator_qqp.zip

**Comment by DurgaSandeep25** [comment]
No, even these also not working. When i click the link, it is not getting redirected to any page.

**Comment by tomhosking** [comment]
GitHub is doing something weird to the links - if you copy the url into a new tab, does the download start then?

**Comment by DurgaSandeep25** [comment]
Yes now its working, if I copy and do it. It is getting downloaded. Thank you so much Tom.

**Comment by tomhosking** [comment]
OK great - please let me know if you have any other problems :)
