### ISSUE TITLE
Getting Error when installing using requirements.txt

### ISSUE THREAD

**Issue by DurgaSandeep25** [tomhosking/separator#2]
Hey Tom
![Query](https://user-images.githubusercontent.com/38128597/123228406-0a4ea600-d4f3-11eb-81d4-88d825c477b9.PNG)
, I am trying to get the results of your trained models in my local machine. When I am trying to install dependencies using "python -m pip install -r requirements.txt", I am getting the following error. Can u help me out here? Thanks :)

**Comment by tomhosking** [comment]
Hi, please update your local repo with `git pull` and try again :)

**Comment by DurgaSandeep25** [comment]
I am new to git. So, can u write the command please? Or is it better to download the source code of torchseq and manually install it?

**Comment by tomhosking** [comment]
Sorry - I mean, update the `separator` repo. Running `git pull` in that working directory should do the trick. I've updated the `requirements.txt` file, it should work now.

**Comment by DurgaSandeep25** [comment]
Okay. Now I am getting some errors with the torch and the versions mentioned in your torchseq repo are different from these, right?
![Query2](https://user-images.githubusercontent.com/38128597/123235406-746a4980-d4f9-11eb-8e55-69bb4da02e51.PNG)

**Comment by tomhosking** [comment]
Yes, that's strange - the `requirements.txt` should be pointing at `torch==1.8.0` (although it should work fine with 1.7 or 1.9 too).

Could you try installing `torchseq` manually? Clone the torchseq repo, then run this from the torchseq directory, with your separator env activated:
```
pip install -r requirements.txt
pip install -e .
```

**Comment by DurgaSandeep25** [comment]
Hey I just saw that only torch version having some error. So installed it manually from torch stable versions. Used the following command
pip install torch==1.7.0+cpu -f https://download.pytorch.org/whl/torch_stable.html
then re-run requirements.txt again. I hope we can close this issue. But I am getting some errors with the model now, Will open a new issue now. Is that okay? Thanks :)

**Comment by tomhosking** [comment]
Ok great :)
