### ISSUE TITLE
Runtime Error regarding GPU

### ISSUE THREAD

**Issue by DurgaSandeep25** [tomhosking/separator#3]
Hi Tom, getting errors regarding GPU. I don't have GPU. What are the changes in the package torchseq to work for only CPU users?

**Comment by tomhosking** [comment]
What is the error that is shown? 

The model should be able to run on CPU in theory, but it will be incredibly slow!

**Comment by DurgaSandeep25** [comment]
Following are the errors. And I am trying to get output given an input sentence, Even this inferencing will be slow?
![Query3](https://user-images.githubusercontent.com/38128597/123240838-4a675600-d4fe-11eb-8350-aaafc4971b82.PNG)
![Query4](https://user-images.githubusercontent.com/38128597/123240832-489d9280-d4fe-11eb-819f-ae6806baa4e5.PNG)
![Query5](https://user-images.githubusercontent.com/38128597/123240836-49cebf80-d4fe-11eb-8639-eb42885ecc1b.PNG)

**Comment by DurgaSandeep25** [comment]
I think we need to change the config.json file. In that it is mentioned that there is a gpu. What is your opinion on this? Is this only for training?
![Query6](https://user-images.githubusercontent.com/38128597/123241493-d5485080-d4fe-11eb-8388-98774b79130c.PNG)

**Comment by tomhosking** [comment]
The problem was that the saved checkpoint was generated on a GPU - I've patched `torchseq` to account for this, if you install from the latest version (`pip install git+https://github.com/tomhosking/torchseq.git`) it should work fine. 

Inference isn't actually too slow on CPU :)

**Comment by DurgaSandeep25** [comment]
Hi Tom, I am able to solve all the errors. Now it's working. Actually, there are 4 to 5 changes in the source code of torchseq itself. if possible i could point out those to you.

**Comment by tomhosking** [comment]
Yes, please let me know if you had to change other code to get it to run?

**Comment by DurgaSandeep25** [comment]
Sure. Let me talk about first error. Tokenizer() function in the torchseq/utils/tokenizer.py requires a input argument i.e model_slug. Shown below for reference.
![Error1](https://user-images.githubusercontent.com/38128597/123249125-463f3680-d506-11eb-9c49-49d475c92f70.PNG)
But in the torchseq/datasets/json_dataset.py, we didnt give any arguments.
![Error4](https://user-images.githubusercontent.com/38128597/123249117-450e0980-d506-11eb-97ec-d06f433b6e70.PNG)
So I changed it and gave an empty string in json_dataset.py then changed the Tokenizer class in tokenizer.py --> else statement
![Error2](https://user-images.githubusercontent.com/38128597/123249114-44757300-d506-11eb-83dd-647a1c5fbc44.PNG)
Previously else statement was like below pic.
![Error5](https://user-images.githubusercontent.com/38128597/123249121-45a6a000-d506-11eb-87d2-5138fcee9845.PNG)
I changed it to available pretrained-vocabs bert-base-uncased. 
![Error3](https://user-images.githubusercontent.com/38128597/123249108-42abaf80-d506-11eb-82a8-3b9f5c9805c6.PNG)

**Comment by tomhosking** [comment]
Good spot! This usually gets initialised by the `Agent` object, but that's created after the dataset in my example. I will update the example code.

**Comment by tomhosking** [comment]
Could you confirm what method/command you're using to run the model?

**Comment by DurgaSandeep25** [comment]
Yeah I am running it in the jupyter notebook conda environment. Code is from your GitHub example itself. I did not change the notebook code at all. 
![Error7](https://user-images.githubusercontent.com/38128597/123251035-5fe17d80-d508-11eb-9593-3e37be118958.PNG)

**Comment by tomhosking** [comment]
OK thanks - the `model_slug` argument should get set by the `ParaphraseAgent` in that example, so shouldn't need the changes you made.

**Comment by DurgaSandeep25** [comment]
I think there might be problems in training because in the config.json, the setting of cuda:true. This might raise some error, not sure of it Tom.
![Query6](https://user-images.githubusercontent.com/38128597/123251590-ff067500-d508-11eb-90bd-3c0c2e12a168.PNG)

Anyways, Thank you so much for your help. :)

**Comment by tomhosking** [comment]
Glad you got it working, and thanks for your patience :)
