### ISSUE TITLE
Confused about the paralex dataset

### ISSUE THREAD

**Issue by yangkexin** [tomhosking/separator#4]
Hi, I find there are four sub-datasets in the paralex fold after downloading the zip file. Meanwhile, the train/test/dev sizes of datasets are almost different in " wikianswers-triples-chunk-extendstop-realexemplars-resample-drop30-N5-R100",  " wikianswers-para-allqs", and "wikianswers-para-splitforgeneval".  Could you please highlight the file finally used in your experiments? :)

**Comment by tomhosking** [comment]
Hi, the dataset wikianswers-triples-chunk-extendstop-realexemplars-resample-drop30-N5-R100 was used to train the model, so it includes the exemplars. The dataset wikianswers-para-split-for-eval is the one used to evaluate the model - it contains a single question to be used as the input, and the remainder of the cluster to be used as references. The dataset wikianswers-pp contains the full paraphrase clusters. I hope that makes sense!

**Comment by yangkexin** [comment]
I got it! thank you~
