### ISSUE TITLE
generating multiple paraphrases of an input sentence

### ISSUE THREAD

**Issue by tejas-gokhale** [tomhosking/separator#5]
Hi Tom, 

Thanks for releasing Separator!  I am using it on a custom set of sentences as shown here : https://github.com/tomhosking/separator#run-inference-over-a-custom-dataset

I would like to generate "n" paraphrased questions for each input questions (say n=5).
Is there a way to do this when calling `instance.inference` as shown below?
```
# Finally, run inference
_, _, (pred_output, _, _), _ = instance.inference(data_loader.test_loader)
```

My apologies if there is a straighforward solution; I am not very familiar with torchseq.
Thanks!
Tejas.

**Comment by tomhosking** [comment]
Hi Tejas,

The model only predicts the top-1 template - but you can get the system to output more of the candidates generated by beam search. Add these settings to the config to increase the beam width to 8, and return the top 5 generated paraphrases:

```
cfg_dict["beam_search"]["beam_width"] = 8
cfg_dict["beam_search"]["beam_expansion"] = 8
cfg_dict["eval"]["topk"] = 5
```

In general, beam search doesn't have that much diversity between outputs, though.
