### ISSUE TITLE
'JsonDataLoader' object has no attribute 'test_loader'

### ISSUE THREAD

**Issue by Soulmates2** [tomhosking/separator#6]
After installing torchseq, I try to replicate the result with the command below:
`torchseq --load ./models/separator-qqp-v1.2 --test`
`torchseq --load ./models/separator-qqp-v1.2 --validate`

However, the following errors occur:
![image](https://user-images.githubusercontent.com/46233964/139359119-b05417b9-23fa-43a1-a680-2dd4d9277499.png)
![image](https://user-images.githubusercontent.com/46233964/139359167-b6768b8d-d833-4941-b819-1b2bde5ee31a.png)

How can I solve this problem?

**Comment by tomhosking** [comment]
Hi, this means that it couldn't find the dataset (I should improve the error message!) - there should be a folder `./data/training-triples/qqp-clusters-chunk-extendstop-realexemplars-resample-drop30-N5-R100` with three `jsonl` files in it, as well as `./data/qqp-splitforgeneval`, `./data/qqp-clusters` and `./data/qqp-allqs`.
