### ISSUE TITLE
how to infer a different discrete syntactic encoding during generation ?

### ISSUE THREAD

**Issue by linhaow** [tomhosking/separator#7]
Thanks for your great work! However, in your paper, it mentioned " we can generate diverse paraphrases of an input question at test time by inferring a different discrete syntactic encoding". I wonder how can I achieve this?

**Comment by tomhosking** [comment]
Hi, thanks for your interest! Do you want to generate a single paraphrase for an input, or multiple paraphrases? 

If you just want a single paraphrase, you can use the code snippet [here](https://github.com/tomhosking/separator#run-inference-over-a-custom-dataset). 

Generating multiple paraphrases is a bit tricker, there's code to do it in [this function](https://github.com/tomhosking/torchseq/blob/d7177567f4a09e0ddddf30bc1d05bff1314824fc/torchseq/metric_hooks/sep_ae.py#L854) but this will need a little bit of adaptation to run in a script.

**Comment by linhaow** [comment]
Thanks for your reply! Yes, I want to generate multiple paraphrases for an input with giving different syntactic encoding index (the codebook). maybe the second link is right for me, I may need some time to adapt it.

**Comment by tomhosking** [comment]
Here's a snippet to generate the top-k predictions (it uses an updated version of the topk prediction code):

The main idea is that we have to first sample the top-k codes from the code prediction model, then go through these in sequence and generate the actual paraphrases from the codes.

Change the values in `examples` to whatever data you want to evaluate on and `path_to_model` to the model that most closely matches the domain you're evaluating on.

```
from torchseq.metric_hooks.sep_ae import SepAEMetricHook

import json
from torchseq.agents.para_agent import ParaphraseAgent
from torchseq.datasets.json_loader import JsonDataLoader
from torchseq.utils.config import Config

import torch

path_to_model = './models/separator-wa'

examples = [
    {'sem_input': 'What is the weight of an average moose?'}
]


with open(path_to_model + "/config.json") as f:
    cfg_dict = json.load(f)
    
config = Config(cfg_dict)

cfg_dict["env"]["data_path"] = "../data/"

# Create the dataset and model
config = Config(cfg_dict)

checkpoint_path = path_to_model + "/model/checkpoint.pt"
instance = ParaphraseAgent(config=config, run_id=None, output_path=None, silent=False, verbose=False, training_mode=False)
instance.load_checkpoint(checkpoint_path)
instance.model.eval()


def get_topk_predictions(
    config,
    agent,
    test=False,
    use_qqp=False,
    mask_length=0,
    top_k=3,
    dev_samples=None,
    test_samples=None,
    skip_scores=False,
):

    sample_outputs = agent.config.eval.get("sample_outputs", True)

    # Generate encodings
    logger.info("Generating encodings for eval set")
    config_gen_eval = copy.deepcopy(config.data)
    config_gen_eval["dataset"] = "json"
    config_gen_eval["json_dataset"] = {
        "path": config.eval.metrics.sep_ae.eval_dataset,
        "field_map": [
            {"type": "copy", "from": "sem_input", "to": "s2"},
            {"type": "copy", "from": "sem_input", "to": "template"},
            {"type": "copy", "from": "sem_input", "to": "s1"},
        ],
    }
    config_gen_eval["eval"]["topk"] = 1

    data_loader = JsonDataLoader(
        config=Config(config_gen_eval), dev_samples=dev_samples, test_samples=test_samples
    )

    config.eval.data["sample_outputs"] = False

    post_bottleneck = "_after_bottleneck" if config.bottleneck.code_predictor.get("post_bottleneck", False) else ""

    _, _, (_, _, _), memory_eval = agent.inference(
        data_loader.test_loader if test else data_loader.valid_loader,
        memory_keys_to_return=[f"sep_encoding_1{post_bottleneck}", f"sep_encoding_2{post_bottleneck}", "vq_codes"],
    )

    X_eval = torch.cat(
        [
            memory_eval[f"sep_encoding_1{post_bottleneck}"][:, 0, :],
            memory_eval[f"sep_encoding_2{post_bottleneck}"][:, 0, :],
        ],
        dim=1,
    )
    y_eval = memory_eval["vq_codes"]

    # Get top-k predicted codes

    logger.info("Running code predictor")

    if agent.model.code_predictor.config.get("beam_width", 0) < top_k:
        agent.model.code_predictor.config.data["beam_width"] = top_k

    pred_codes = []
    # # TODO: batchify!
    for ix, x_batch in enumerate(tqdm(X_eval, desc="Predicting codes")):
        curr_codes = agent.model.code_predictor.infer(
            x_batch.unsqueeze(0).to(agent.device), {}, top_k=top_k
        )
        pred_codes.append(curr_codes)

    pred_codes = torch.cat(pred_codes, dim=0)

    config_pred_diversity = copy.deepcopy(config.data)
    config_pred_diversity["dataset"] = "json"
    config_pred_diversity["json_dataset"] = {
        "path": config.eval.metrics.sep_ae.eval_dataset,
        "field_map": [
            {"type": "copy", "from": "sem_input", "to": "s2"},
            {"type": "copy", "from": "sem_input", "to": "template"},
            {"type": "copy", "from": "sem_input", "to": "s1"},
            {"type": "copy", "from": "forced_codes", "to": "forced_codes"},
        ],
    }
    config_pred_diversity["eval"]["topk"] = 1

    data_loader = JsonDataLoader(
        config=Config(config_pred_diversity), dev_samples=dev_samples, test_samples=test_samples
    )

    config.eval.data["sample_outputs"] = True

    split = "test" if test else "dev"

    with jsonlines.open(
        os.path.join(
            config.env.data_path,
            config.eval.metrics.sep_ae.eval_dataset,
            f"{split}.jsonl",
        )
    ) as f:
        rows = [row for row in f][: config_pred_diversity["eval"].get("truncate_dataset", None)]

    refs = [q["paras"] for q in rows]
    inputs = [[q["sem_input"]] for q in rows]

    max_num_refs = max([len(x) for x in refs])
    refs_padded = [x + [x[0]] * (max_num_refs - len(x)) for x in refs]

    scores = {}
    topk_outputs = []

    for k in range(top_k):
        logger.info(f"Running generation with {k+1}th best codes")

        samples = (data_loader._test if test else data_loader._valid).samples
        samples = [{**x, "forced_codes": pred_codes[i, k, :].tolist()} for i, x in enumerate(samples)]
        forced_loader = JsonDataLoader(config=Config(config_pred_diversity), dev_samples=samples)

        _, _, (output, _, _), _ = agent.inference(forced_loader.valid_loader)

        if not skip_scores:
            tgt_bleu = sacrebleu.corpus_bleu(output, list(zip(*refs_padded)), lowercase=True).score
            self_bleu = sacrebleu.corpus_bleu(output, list(zip(*inputs)), lowercase=True).score

            alpha = config.eval.metrics.sep_ae.get("ibleu_alpha", 0.8)
            ibleu = alpha * tgt_bleu - (1 - alpha) * self_bleu

            scores[k + 1] = (tgt_bleu, self_bleu, ibleu)

        topk_outputs.append(output)

    if not skip_scores:
        # calculate p-BLEU (Cao and Wan, 2020)
        # p-BLEU = sum_i, sum_{j neq i} BLEU(yi, yj) / k * (k-1)
        pbleu_scores = []
        for i in range(top_k):
            for j in range(top_k):
                if i == j:
                    continue
                this_bleu = sacrebleu.corpus_bleu(
                    topk_outputs[i], list(zip(*[[x] for x in topk_outputs[j]])), lowercase=True
                ).score
                pbleu_scores.append(this_bleu)
        scores["pbleu"] = np.mean(pbleu_scores)

    agent.config.eval.data["sample_outputs"] = sample_outputs

    return scores, topk_outputs

_, pred_output = get_topk_predictions(config, instance, dev_samples=examples, top_k=3, skip_scores=True)
```

**Comment by linhaow** [comment]
thanks for your code, however,  I got this following error . What should I do 

TypeError: infer() got an unexpected keyword argument 'outputs_to_block'

**Comment by linhaow** [comment]
I just follow the readme  and execute "pip install -r requirements". However I got wrong in this code

**Comment by tomhosking** [comment]
Sorry, that's my fault - the snippet above uses a newer version of TorchSeq (but the Separator checkpoints aren't compatible with this). I've updated the snippet to ignore that argument. Please let me know if you have any other issues, there may be other parts of the code that use the newer TorchSeq version.

**Comment by linhaow** [comment]
Thanks a lot for your replying. But I still met some problems as follow:
Traceback (most recent call last):
  File "predict_exampler.py", line 177, in <module>
    _, pred_output = get_topk_predictions(config, instance, dev_samples=examples, top_k=3, skip_scores=True)
  File "predict_exampler.py", line 92, in get_topk_predictions
    for ix, x_batch in enumerate(tqdm(X_eval, desc="Predicting codes")):
TypeError: 'module' object is not callable

**Comment by linhaow** [comment]
I found there are many other issues and I don't know how to deal them, Could you debug it with a virtual envs ( like conda)? It will really helps if so!

**Comment by tomhosking** [comment]
Hi, sorry about this - the best thing to do will be to use the latest version of TorchSeq:

```
pip install git+https://github.com/tomhosking/torchseq.git@v2.1
```

Then, download a pretrained model that is compatible with this version:
[Paralex (v2)](https://tomho.sk/models/separator/separator_paralex_v2.zip)
[QQP (v2)](https://tomho.sk/models/separator/separator_qqp_v2.zip)

Finally, use the following code to sample mutliple paraphrases (you may need to change the paths to the model and vocabs). I've tested it this time, but please let me know if you have any problems getting it to work.

```
from torchseq.metric_hooks.sep_ae import SepAEMetricHook

import json
from torchseq.agents.para_agent import ParaphraseAgent
from torchseq.datasets.json_loader import JsonDataLoader
from torchseq.utils.config import Config

import torch

path_to_model = './models/separator-wa-v2'

examples = [
    {'sem_input': 'How can I generate multiple paraphrases?'}
]

import logging

logger = logging.getLogger("SepAEMetric")

with open(path_to_model + "/config.json") as f:
    cfg_dict = json.load(f)
    
config = Config(cfg_dict)

cfg_dict["env"]["data_path"] = "./data/"

# Create the dataset and model
config = Config(cfg_dict)

checkpoint_path = path_to_model + "/model/checkpoint.pt"
instance = ParaphraseAgent(config=config, run_id=None, output_path=None, silent=False, verbose=False, training_mode=False)
instance.load_checkpoint(checkpoint_path)
instance.model.eval()

_, pred_output = SepAEMetricHook.eval_gen_codepred_diversity(config, instance, dev_samples=examples, top_k=3, skip_scores=True)


print(pred_output)
```

**Comment by linhaow** [comment]
Thanks for your reply, but I still got this error:
Traceback (most recent call last):
  File "predict_exampler.py", line 35, in <module>
    instance.load_checkpoint(checkpoint_path)
  File "/anaconda/envs/sep/lib/python3.7/site-packages/torchseq/agents/model_agent.py", line 166, in load_checkpoint
    missing_keys, unexpected_keys = self.model.load_state_dict(checkpoint["model_state_dict"], strict=False)
  File "/anaconda/envs/sep/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1052, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for BottleneckAutoencoderModel:
        size mismatch for bottleneck.quantizer._alpha: copying a param with shape torch.Size([16]) from checkpoint, the shape in current model is torch.Size([4]).

**Comment by linhaow** [comment]
Thanks for your reply, I still have some errors, why should I provide this file?
Traceback (most recent call last):
  File "predict_exampler.py", line 38, in <module>
    _, pred_output = SepAEMetricHook.eval_gen_codepred_diversity(config, instance, dev_samples=examples, top_k=3, skip_scores=True)
  File "/anaconda/envs/sep/lib/python3.7/site-packages/torchseq/metric_hooks/sep_ae.py", line 954, in eval_gen_codepred_diversity
    f"{split}.jsonl",
  File "/anaconda/envs/sep/lib/python3.7/site-packages/jsonlines/jsonlines.py", line 322, in open
    fp = builtins.open(name, mode=mode + "t", encoding="utf-8")
FileNotFoundError: [Errno 2] No such file or directory: './data/wikianswers-para-splitforgeneval/dev.jsonl'

**Comment by tomhosking** [comment]
This approach is using the built-in evaluation code, which is designed to calculate iBLEU scores compared to references. It loads that file to use as references (although you don't need it for what you're doing). You can download the dataset files [here](http://tomho.sk/models/separator/data_paralex.zip) to make the error go away.

**Comment by linhaow** [comment]
It works, Thank you very much !

**Comment by tomhosking** [comment]
Great! Thanks for your patience :)
