### ISSUE TITLE
size mismatch for bottleneck.quantizer._alpha: copying a param with shape torch.Size([4]) from checkpoint, the shape in current model is torch.Size([16]).

### ISSUE THREAD

**Issue by marcoschwartz** [tomhosking/separator#8]
Hello,

I am trying to reproduce your results but I have the following error when I run the command:

torchseq --load ./models/separator-qqp-v1.2 --test --cpu

The error is:

size mismatch for bottleneck.quantizer._alpha: copying a param with shape torch.Size([4]) from checkpoint, the shape in current model is torch.Size([16]).

Any idea how to debug this? I put the model in the right folder and also the data in the data folder.

Thanks!

**Comment by tomhosking** [comment]
Hi, could you check that you installed the right version of torchseq? It needs to be the tag linked from the readme, eg `pip install git+https://github.com/tomhosking/torchseq.git@separator-v1.2`. The pretrained checkpoints linked aren't compatible with the latest version (although you can download some that are from here: https://tomho.sk/models/separator/)

**Comment by marcoschwartz** [comment]
Hi, thanks for the answer! Indeed that might be the issue - I installed the latest version of torchseq. I'll try again with the version you mentioned.
